[main]
font=JetBrainsMono Nerd Font:size=11
dpi-aware=yes

[colors]
alpha=0.88
background=1a1b26
foreground=a9b1d6

[colors.regular0]
# black
32344a
[colors.regular1]
# red
f7768e
[colors.regular2]
# green
9ece6a
[colors.regular3]
# yellow
e0af68
[colors.regular4]
# blue
7aa2f7
[colors.regular5]
# magenta
bb9af7
[colors.regular6]
# cyan
449dab
[colors.regular7]
# white
787c99

[colors.bright0]
# bright black
444b6a
[colors.bright1]
# bright red
ff7a93
[colors.bright2]
# bright green
b9f27c
[colors.bright3]
# bright yellow
ff9e64
[colors.bright4]
# bright blue
7da6ff
[colors.bright5]
# bright magenta
bb9af7
[colors.bright6]
# bright cyan
0db9d7
[colors.bright7]
# bright white
acb0d0

[cursor]
style=beam
color=1a1b26 a9b1d6

[scrollback]
lines=10000

[key-bindings]
search-start=Control+Shift+r
